var annotated =
[
    [ "AnimationPlugin", "namespaceAnimationPlugin.html", "namespaceAnimationPlugin" ],
    [ "CameraManipPlugin", "namespaceCameraManipPlugin.html", "namespaceCameraManipPlugin" ],
    [ "compile_time_utils", "namespacecompile__time__utils.html", "namespacecompile__time__utils" ],
    [ "DummyPlugin", "namespaceDummyPlugin.html", "namespaceDummyPlugin" ],
    [ "Eigen", "namespaceEigen.html", null ],
    [ "globjects", "namespaceglobjects.html", null ],
    [ "MeshFeatureTrackingPlugin", "namespaceMeshFeatureTrackingPlugin.html", "namespaceMeshFeatureTrackingPlugin" ],
    [ "MeshPaintPlugin", "namespaceMeshPaintPlugin.html", "namespaceMeshPaintPlugin" ],
    [ "OpenMesh", "namespaceOpenMesh.html", "namespaceOpenMesh" ],
    [ "Qt_utils", "namespaceQt__utils.html", null ],
    [ "Ra", "namespaceRa.html", "namespaceRa" ],
    [ "SkinningPlugin", "namespaceSkinningPlugin.html", "namespaceSkinningPlugin" ],
    [ "Super4PCS", "namespaceSuper4PCS.html", "namespaceSuper4PCS" ],
    [ "Ui", "namespaceUi.html", null ],
    [ "UI", "namespaceUI.html", null ],
    [ "AnimationUI", "classAnimationUI.html", "classAnimationUI" ],
    [ "CameraManipUI", "classCameraManipUI.html", "classCameraManipUI" ],
    [ "FeatureData", "structFeatureData.html", "structFeatureData" ],
    [ "FILELog", "classFILELog.html", null ],
    [ "Log", "classLog.html", "classLog" ],
    [ "MeshFeatureTrackingUI", "classMeshFeatureTrackingUI.html", "classMeshFeatureTrackingUI" ],
    [ "MeshPaintUI", "classMeshPaintUI.html", "classMeshPaintUI" ],
    [ "Output2FILE", "classOutput2FILE.html", "classOutput2FILE" ],
    [ "QAbstractItemModel", "classQAbstractItemModel.html", null ],
    [ "QApplication", "classQApplication.html", null ],
    [ "QFrame", "classQFrame.html", null ],
    [ "QItemSelectionModel", "classQItemSelectionModel.html", null ],
    [ "QMainWindow", "classQMainWindow.html", null ],
    [ "QObject", "classQObject.html", null ],
    [ "QWindow", "classQWindow.html", null ],
    [ "TaskParams", "classRa_1_1Core_1_1TaskParams.html", null ]
];