
# EXTERNALS
# have ExternalProject available
include(ExternalProject)

# here is defined the way we want to import glm
ExternalProject_Add(
    radium_libs

    # where the source will live
    SOURCE_DIR "${CMAKE_SOURCE_DIR}/src"

    # override default behaviours
    UPDATE_COMMAND ""

    # set the installatin to root
    # INSTALL_COMMAND cmake -E echo "Skipping install step."
    INSTALL_DIR "${CMAKE_INSTALL_PREFIX}"
    CMAKE_GENERATOR ${CMAKE_GENERATOR}
    CMAKE_GENERATOR_TOOLSET ${CMAKE_GENERATOR_TOOLSET}
    CMAKE_ARGS
        -DRADIUM_WITH_DOUBLE_PRECISION=${RADIUM_WITH_DOUBLE_PRECISION}
        -DRADIUM_WITH_OMP=${RADIUM_WITH_OMP}
        -DRADIUM_WITH_FANCY_GL=${RADIUM_WITH_FANCY_GL}
        -DRADIUM_WITH_TEXTURES=${RADIUM_WITH_TEXTURES}
        -DRADIUM_WITH_PROFILING=${RADIUM_WITH_PROFILING}
        -DRADIUM_WARNINGS_AS_ERRORS=${RADIUM_WARNINGS_AS_ERRORS}
        -DRADIUM_FORCE_ASSERTS=${RADIUM_FORCE_ASSERTS}
        -DRADIUM_ASSIMP_SUPPORT=${RADIUM_ASSIMP_SUPPORT}
        -DRADIUM_TINYPLY_SUPPORT=${RADIUM_TINYPLY_SUPPORT}
        -DRADIUM_BUILD_APPS=${RADIUM_BUILD_APPS}
        -DRADIUM_FAST_MATH=${RADIUM_FAST_MATH}
        -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
        -DCMAKE_BUILD_TYPE=${RADIUM_SUBMODULES_BUILD_TYPE}
        -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
        -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
        -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}
        -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
        -DCMAKE_CXX_FLAGS_DEBUG=${CMAKE_CXX_FLAGS_DEBUG}
        -DCMAKE_CXX_FLAGS_RELEASE=${CMAKE_CXX_FLAGS_RELEASE}
        -DCMAKE_CXX_FLAGS_RELWITHDEBINFO=${CMAKE_CXX_FLAGS_RELWITHDEBINFO}
        -DCMAKE_SHARED_LINKER_FLAGS=${CMAKE_SHARED_LINKER_FLAGS}
        -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
    STEP_TARGETS install
    EXCLUDE_FROM_ALL TRUE
)

add_custom_target(radium_libraries DEPENDS radium_libs)
